import { M_PLUS_1 } from "next/font/google";
import "./globals.scss";

const inter = M_PLUS_1({
  subsets: ["latin-ext"],
  weight: ["300", "400", "700", "100", "900", "500"],
});

export const metadata = {
  title: "Gen Funnels",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
